changing fare_class to fare_period
osplanning-data-standards/GTFS-PLUS pull request #27
Opened 2016-09-15 17:38 UTC by stefancoe

Please review change.

2016-09-15 18:11 UTC, e-lo commented on files/fare_transfer_rules_ft.md
> +`from_fare_period`	| An ID that identifies the `fare_period` that the passenger is coming from.
Hmm, this part seems a little odd.  Would it not be `from_fare_id`..etc?

2016-09-15 18:13 UTC, e-lo commented on files/fare_rules_ft.md
> +`fare_period`		| Contains the name of the `fare_period` that links to the same attribute in `routes_ft.txt`.
fare_class was removed form routes_ft... so so should fare_period

2016-09-15 18:14 UTC, e-lo commented on files/fare_rules_ft.md
> +`fare_period`		| Contains the name of the `fare_period` that links to the same attribute in `routes_ft.txt`.
is fare_period a unique identifier?  If so, we should note.

2016-09-15 18:14 UTC, e-lo requested changes
Thanks for getting this started, @stefancoe !  I think there are a few needed mods, but @lmz should also review.
Thanks!

2016-09-15 18:20 UTC, stefancoe commented
No problem.Yeah, it looks like fares.md needs to be updated as well. I'll
try getting to that today or tomorrow. Thanks,

Stefan


On Thu, Sep 15, 2016 at 11:14 AM, Elizabeth Sall <notifications@github.com>
wrote:

> *@e-lo* requested changes on this pull request.
>
> Thanks for getting this started, @stefancoe <https://github.com/stefancoe>
> ! I think there are a few needed mods, but @lmz <https://github.com/lmz>
> should also review.
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/osplanning-data-standards/GTFS-PLUS/pull/27#pullrequestreview-223335>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABPhR-3mQrwXKN1pMvSWHZL7_tW62_Ksks5qqYsNgaJpZM4J-IwO>
> .
>

2016-10-04 18:36 UTC, lmz commented on files/fare_transfer_rules_ft.md
> +`from_fare_period`	| An ID that identifies the `fare_period` that the passenger is coming from.
Hmm... The fares are now specified by fare_period so I think it should be fare_period?  But it does get a bit confusing... like would we need bart_pm to muni_pm and muni_ev if it's possible that the transfer could cross time periods?  :(

2016-10-04 18:39 UTC, lmz commented on files/fare_rules_ft.md
> +`fare_period`		| Contains the name of the `fare_period` that links to the same attribute in `routes_ft.txt`.
Yes.  Also this is essentially where we define fare_periods, so maybe we could name the file fare_periods_ft.txt instead of fare_rules_ft.txt?  'Cos right now, I can never remember which file has what...

2016-10-05 19:58 UTC, stefancoe commented on files/fare_transfer_rules_ft.md
> +`from_fare_period`	| An ID that identifies the `fare_period` that the passenger is coming from.
yeah, i think that is the idea- to model time of day specific fares, including transfers. Fare_id does not give time of day specific information.

2016-11-16 23:11 UTC, merged